// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: account.sql

package sqlc

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (full_name, account_number, balance)
VALUES ($1, $2, $3)
RETURNING id, full_name, balance, account_number, created_at, updated_at
`

type CreateAccountParams struct {
	FullName      string
	AccountNumber string
	Balance       int64
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.FullName, arg.AccountNumber, arg.Balance)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Balance,
		&i.AccountNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts 
WHERE id = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAccount, id)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, full_name, balance, account_number, created_at, updated_at FROM accounts
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAccount(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Balance,
		&i.AccountNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByNumber = `-- name: GetAccountByNumber :one
SELECT id, full_name, balance, account_number, created_at, updated_at FROM accounts
WHERE account_number = $1 LIMIT 1
`

func (q *Queries) GetAccountByNumber(ctx context.Context, accountNumber string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByNumber, accountNumber)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Balance,
		&i.AccountNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, full_name, balance, account_number, created_at, updated_at FROM accounts
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAccountsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccounts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Balance,
			&i.AccountNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBalance = `-- name: UpdateBalance :one
UPDATE accounts
SET balance = balance + $2
WHERE id = $1
RETURNING id, full_name, balance, account_number, created_at, updated_at
`

type UpdateBalanceParams struct {
	ID      int64
	Balance int64
}

func (q *Queries) UpdateBalance(ctx context.Context, arg UpdateBalanceParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateBalance, arg.ID, arg.Balance)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Balance,
		&i.AccountNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
