// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID            int64
	FullName      string
	Balance       int64
	AccountNumber string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Mutation struct {
	ID              int64
	AccountID       int64
	TransferID      uuid.UUID
	Amount          int64
	PreviousBalance int64
	CurrentBalance  int64
	CreatedAt       time.Time
}

type Transfer struct {
	ID              uuid.UUID
	FromAccountID   int64
	ToAccountID     int64
	Amount          int64
	ReferenceNumber string
	Status          string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type User struct {
	ID           uuid.UUID
	Username     string
	PasswordHash string
	Email        string
	AccountID    pgtype.Int8
	Role         string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
