// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: mutation.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createMutation = `-- name: CreateMutation :one
INSERT INTO mutations (account_id, transfer_id, amount, previous_balance, current_balance)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, account_id, transfer_id, amount, previous_balance, current_balance, created_at
`

type CreateMutationParams struct {
	AccountID       int64
	TransferID      uuid.UUID
	Amount          int64
	PreviousBalance int64
	CurrentBalance  int64
}

func (q *Queries) CreateMutation(ctx context.Context, arg CreateMutationParams) (Mutation, error) {
	row := q.db.QueryRow(ctx, createMutation,
		arg.AccountID,
		arg.TransferID,
		arg.Amount,
		arg.PreviousBalance,
		arg.CurrentBalance,
	)
	var i Mutation
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TransferID,
		&i.Amount,
		&i.PreviousBalance,
		&i.CurrentBalance,
		&i.CreatedAt,
	)
	return i, err
}

const listMutationsByAccount = `-- name: ListMutationsByAccount :many
SELECT
    m.id,
    m.amount,
    m.previous_balance,
    m.current_balance,
    m.created_at,
    t.reference_number,
    CASE
        WHEN t.from_account_id = m.account_id THEN 'DEBIT'
        ELSE 'CREDIT'
    END as type
FROM mutations m
JOIN transfers t ON t.id = m.transfer_id
WHERE m.account_id = (SELECT id FROM accounts WHERE account_number = $1)
ORDER BY m.created_at DESC
LIMIT $2 OFFSET $3
`

type ListMutationsByAccountParams struct {
	AccountNumber string
	Limit         int32
	Offset        int32
}

type ListMutationsByAccountRow struct {
	ID              int64
	Amount          int64
	PreviousBalance int64
	CurrentBalance  int64
	CreatedAt       time.Time
	ReferenceNumber string
	Type            string
}

func (q *Queries) ListMutationsByAccount(ctx context.Context, arg ListMutationsByAccountParams) ([]ListMutationsByAccountRow, error) {
	rows, err := q.db.Query(ctx, listMutationsByAccount, arg.AccountNumber, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMutationsByAccountRow
	for rows.Next() {
		var i ListMutationsByAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.PreviousBalance,
			&i.CurrentBalance,
			&i.CreatedAt,
			&i.ReferenceNumber,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
