// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: report.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const dailyTransactionReport = `-- name: DailyTransactionReport :many
SELECT
    DATE(created_at) as date,
    COUNT(*) as transaction_count,
    SUM(amount) as total_amount,
    SUM(CASE WHEN status = 'SUCCESS' THEN amount ELSE 0 END) as success_amount,
    SUM(CASE WHEN status = 'FAILED' THEN amount ELSE 0 END) as failed_amount
FROM transfers
WHERE created_at >= $1 AND created_at <= $2
GROUP BY DATE(created_at)
ORDER BY DATE(created_at) DESC
`

type DailyTransactionReportParams struct {
	CreatedAt   time.Time
	CreatedAt_2 time.Time
}

type DailyTransactionReportRow struct {
	Date             pgtype.Date
	TransactionCount int64
	TotalAmount      int64
	SuccessAmount    int64
	FailedAmount     int64
}

func (q *Queries) DailyTransactionReport(ctx context.Context, arg DailyTransactionReportParams) ([]DailyTransactionReportRow, error) {
	rows, err := q.db.Query(ctx, dailyTransactionReport, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailyTransactionReportRow
	for rows.Next() {
		var i DailyTransactionReportRow
		if err := rows.Scan(
			&i.Date,
			&i.TransactionCount,
			&i.TotalAmount,
			&i.SuccessAmount,
			&i.FailedAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAccountSummary = `-- name: GetAccountSummary :one
SELECT
    COUNT(*) as total_transactions,
    SUM(CASE WHEN status = 'SUCCESS' THEN 1 ELSE 0 END) as success_count,
    SUM(CASE WHEN status = 'FAILED' THEN 1 ELSE 0 END) as failed_count,
    COALESCE(SUM(CASE WHEN from_account_id = $1 AND status = 'SUCCESS' THEN amount END), 0) as total_outgoing,
    COALESCE(SUM(CASE WHEN to_account_id = $1 AND status = 'SUCCESS' THEN amount END), 0) as total_incoming
FROM transfers
WHERE from_account_id = $1 OR to_account_id = $1
`

type GetAccountSummaryRow struct {
	TotalTransactions int64
	SuccessCount      int64
	FailedCount       int64
	TotalOutgoing     interface{}
	TotalIncoming     interface{}
}

func (q *Queries) GetAccountSummary(ctx context.Context, fromAccountID int64) (GetAccountSummaryRow, error) {
	row := q.db.QueryRow(ctx, getAccountSummary, fromAccountID)
	var i GetAccountSummaryRow
	err := row.Scan(
		&i.TotalTransactions,
		&i.SuccessCount,
		&i.FailedCount,
		&i.TotalOutgoing,
		&i.TotalIncoming,
	)
	return i, err
}
