// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: audit.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const recordAuditLog = `-- name: RecordAuditLog :one
INSERT INTO audit_logs (
    user_id, action, description, ip_address, user_agent
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING log_id, user_id, action, description, ip_address, user_agent, created_at
`

type RecordAuditLogParams struct {
	UserID      pgtype.UUID
	Action      string
	Description pgtype.Text
	IpAddress   pgtype.Text
	UserAgent   pgtype.Text
}

func (q *Queries) RecordAuditLog(ctx context.Context, arg RecordAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, recordAuditLog,
		arg.UserID,
		arg.Action,
		arg.Description,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i AuditLog
	err := row.Scan(
		&i.LogID,
		&i.UserID,
		&i.Action,
		&i.Description,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}
