// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	AccountID     uuid.UUID
	CustomerID    uuid.UUID
	BranchCode    string
	AccountNumber string
	AccountType   pgtype.Text
	Balance       pgtype.Numeric
	Currency      pgtype.Text
	Status        pgtype.Text
	OpenedDate    pgtype.Date
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type AuditLog struct {
	LogID       uuid.UUID
	UserID      pgtype.UUID
	Action      string
	Description pgtype.Text
	IpAddress   pgtype.Text
	UserAgent   pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

type AuthUser struct {
	UserID       uuid.UUID
	CustomerID   pgtype.UUID
	Username     string
	PasswordHash string
	Role         pgtype.Text
	LastLogin    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Branch struct {
	BranchCode string
	BranchName string
	Address    string
	City       string
	Phone      string
	CreatedAt  pgtype.Timestamptz
}

type Customer struct {
	CustomerID  uuid.UUID
	Nik         string
	FullName    string
	Email       string
	Phone       string
	Address     string
	DateOfBirth pgtype.Date
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type DebitCard struct {
	CardID     uuid.UUID
	AccountID  uuid.UUID
	CardNumber string
	ExpiryDate pgtype.Date
	Cvv        string
	PinHash    string
	DailyLimit pgtype.Numeric
	Status     pgtype.Text
	IssuedDate pgtype.Date
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Transaction struct {
	TransactionID    uuid.UUID
	AccountID        uuid.UUID
	RelatedAccountID pgtype.UUID
	Amount           pgtype.Numeric
	TransactionType  pgtype.Text
	Description      pgtype.Text
	ReferenceNumber  string
	Status           pgtype.Text
	TransactionDate  pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}
